### ISSUE TITLE
Fast sugar cane

### ISSUE THREAD

**Issue by InValidcarFound** [Y0ungSandwich/Mech-Magic-2#2]
not sure if this is supposed to happen, but its a bit broken that I don't think should, if you place sugar cane on snad it in less then a second will grow a new piece, you can repeat this and get a lot of sugar cane in a few seconds.

**Comment by Y0ungSandwich** [comment]
Even after lowering it to minimum growth it stays super fast. With the amount of farms and fertilizers available from other mods we will remove SNAD.
